cpp/src/parquet/encryption/crypto_factory.h
Following discussion in 
https://docs.google.com/document/d/1Tjb45rQ2x9FydFmFIRo-U6PNJnEQ5_CfdCC4EU8M6D0/edit?tab=t.0
Creating a struct that extends the original EncryptionConfiguration and adds the three new parameters needed for external encryption service.
Note:
1. All params are represented as strings, following the column_keys map of the EncryptionConfig. This string is parsed later in crypto_factory.cc, and we will also add parsers when we're ready to convert the config.
2. This is just the definition of the struct. I am not modifying any test because I am not converting this struct or using it anywhere, as this requires a lot more work in crypto_factory.cc, plus extending the ColumnEncryptionProperties object.
3. Sending the struct to review to unblock Cris and his work on the …
=> Adding the basic struct for the ExternalEncryptionConfig

cpp/src/parquet/encryption/encryption.cc, cpp/src/parquet/encryption/encryption.h
Adding the ExternalFileEncryptionProperties.
Subclass of FileEncryptionProperties, now just adding the class definition, builder, constructor.
=> Basic external file encryption properties

cpp/src/parquet/CMakeLists.txt, cpp/src/parquet/encryption/crypto_factory.cc, cpp/src/parquet/encryption/crypto_factory.h, cpp/src/parquet/encryption/crypto_factory_test.cc, cpp/src/parquet/encryption/encryption.h, cpp/src/parquet/encryption/properties_test.cc
Needed to modify some of the previously added classes to get the code working correctly.
Code is not reused as much as I first thought, since the sanity checks at the beginning of the Get method are different for the FileEncryptionProperties and the ExternalFileEncryptionProperties.
CryptoFactory had no unit test (!), so added that as well.
=> Add GetExternalFileEncryptionProperties method to C++ CryptoFactory 

cpp/src/generated/parquet_types.cpp, cpp/src/generated/parquet_types.h, cpp/src/generated/parquet_types.tcc, cpp/src/parquet/encryption/encryption_internal.cc, cpp/src/parquet/encryption/write_configurations_test.cc, cpp/src/parquet/parquet.thrift, cpp/src/parquet/thrift_internal.h, cpp/src/parquet/types.h, python/pyarrow/_parquet.pxd, python/pyarrow/_parquet_encryption.pxd, python/pyarrow/_parquet_encryption.pyx, python/pyarrow/includes/libparquet_encryption.pxd
Add the new enum value for the External DBPA Encryptor.
This change requires us to use thrift generated code. After modifying parquet_thrift and thrift_internal, the command needed to regenerate the code is:
cd cpp
./build-support/update-thrift.sh
=> Add external enum

cpp/src/parquet/encryption/crypto_factory.h, python/pyarrow/_parquet.pxd, python/pyarrow/_parquet.pyx, python/pyarrow/_parquet_encryption.pxd, python/pyarrow/_parquet_encryption.pyx, python/pyarrow/includes/libparquet_encryption.pxd, python/pyarrow/tests/parquet/test_external_encryption.py
As part of #11 this PR is adding the python bindings to use the FileEncryptor
=> Creating the GetExternalFileEncryptionProperties us part of task #26

cpp/src/parquet/encryption/decryptor_interface.h, cpp/src/parquet/encryption/encryptor_interface.h
Adding the basic Encryptor and Decryptor interfaces.
These are intended to abstract away the Aes version of the encryptors and decryptors so user can choose other types to use.
=> Adding the new encryptor and decryptor interfaces

cpp/src/parquet/encryption/internal_file_decryptor.cc, cpp/src/parquet/encryption/internal_file_decryptor.h, cpp/src/parquet/encryption/internal_file_encryptor.cc, cpp/src/parquet/encryption/internal_file_encryptor.h, cpp/src/parquet/file_reader.cc, cpp/src/parquet/file_writer.cc, cpp/src/parquet/metadata.cc, cpp/src/parquet/metadata.h
Expose column information at encryptor and decryptor creation time.
When writing, the ColumnChunkMetaDataBuilder contains information to the column's type, compression, encoding, and format. It also contains a pointer to the WriterProperties, where the ExternalFileEncryptionProperties are found.
At read time, the ColumnChunkMetaData is analogous, and containing a pointer to the ReaderProperties, where the ExternalFileDecryptionProperties are found.
No logic changed here, so no tests are modified. Assigning nullptr as default values so nothing is broken.
=> Exposing column information at encryptor and decryptor creation time

cpp/src/parquet/encryption/crypto_factory.cc, cpp/src/parquet/encryption/crypto_factory_test.cc, python/pyarrow/_parquet_encryption.pyx, python/pyarrow/tests/parquet/test_external_encryption.py, python/scripts/base_app.py
Fixing problems in the ExternalEncryptionConfig Cython bindings.
While debugging PR #57 I noticed the test setup was incorrect (repeated columns in per_column_encryption and column_keys). Since that should've caused exceptions, I started debugging whether the ExternalEncryptionConfig made its way correctly to the Arrow code.
Found and fixed the errors, plus a small bug in crypto_factory.cc related to the footer_key.
Fixed the bindings and the test.
Verified using the base app and sending an ExternalEncryptionConfig and printing out values in the CryptoFactory (there's no good way to test this right now).
Up next, fixing the rest of the existing bindings (ExternalDecryptionConfig and ExternalFileEncryptionProperties) until I make my way back to fixing the code in PR #57
=> Fixing problems in ExternalEncryptionConfig bindings

cpp/src/parquet/encryption/external/dbpa_interface.h, cpp/src/parquet/encryption/external/dbpa_library_wrapper.cc, cpp/src/parquet/encryption/external/dbpa_library_wrapper.h, cpp/src/parquet/encryption/external/dbpa_library_wrapper_test.cc, cpp/src/parquet/encryption/external/dbpa_test_agent.cc, cpp/src/parquet/encryption/external/dbpa_test_agent.h, cpp/src/parquet/encryption/external/enums.h, cpp/src/parquet/encryption/external/loadable_encryptor_utils.cc, cpp/src/parquet/encryption/external/loadable_encryptor_utils.h, cpp/src/parquet/encryption/external/loadable_encryptor_utils_test.cc, cpp/src/parquet/encryption/external/span.hpp
In this change, we are merging-in the latest version of [DataBatchProtectionAgentInterface](https://github.com/protegrity/DataBatchProtectionService/) into the mini-app code branch
- Copying the latest version of `dbpa_interface.h` (and some of the required dependencies, like `enums.h`)
- Updating the code to use `tcb::span` (instead of `std::span`, which cannot be used given that Arrow is C++17 and `std::span` is C++20)
- Modify the `dbpa_library_wrapper` to also decorate the `init()` method (this method was not considered in the earlier version of `dbpa_interface`). Modified the tests to include `init()`
- Modify tests to account for the fact that `EncryptionResult` and `DecryptionResult` are now well defined.
- In `dbpa_library_wrapper`, moved some of the decorated methods to the `*.h` …
=> Adding latest DBPAInterface to dev-miniapp

cpp/src/parquet/CMakeLists.txt, cpp/src/parquet/encryption/encryption_internal.cc, cpp/src/parquet/encryption/encryption_internal.h, cpp/src/parquet/encryption/external/dbpa_utils.cc, cpp/src/parquet/encryption/external/dbpa_utils.h, cpp/src/parquet/encryption/external/loadable_encryptor_utils.cc
In this work, we're wiring the shared library (aka DLL) -loaded DBPAgent instance into both `ExternalEncryptorImpl` and `ExternalDecryptorImpl` (`EEI` and `EDI`, respectively). We're using the miniApp branch for this. 
As part of this change, the previous implementations of `EEI` and `EDI` are being over-written.
As a reminder - this particular PR will never be merged into `dev_phase2` nor into `main` - an equivalent change will be made once the refactoring work happening in `dev_phase2` is complete.
- Addition of `dbpa_utils.h` and `dbpa_utils.cc` as utils to help translate concepts between the Arrow and DBPA namespace.
- Heavily modified `ExternalEncryptorImpl` and `ExternalDecryptorImpl` (inside `encryption_internal.cc` and `encryption_internal.h`). 
- In particular, we modified
- …
=> Wiring DBPAgent into ExternalEncryptorImpl/ExternalDecryptor impl

cpp/src/parquet/CMakeLists.txt, cpp/src/parquet/encryption/aes_encryption.cc, cpp/src/parquet/encryption/aes_encryption.h, cpp/src/parquet/encryption/aes_encryption_nossl.cc, cpp/src/parquet/encryption/aes_encryption_test.cc, cpp/src/parquet/encryption/internal_file_decryptor.cc, cpp/src/parquet/encryption/internal_file_encryptor.cc, cpp/src/parquet/encryption/internal_file_encryptor.h, cpp/src/parquet/encryption/key_toolkit_internal.cc, cpp/src/parquet/metadata.cc
Continuing with the AesEncryptor refactor.
In this next step I rename everything related to encryption_internal as aes_encryption.
Updating all the includes, tests and CMake files.
Verified all encryption unit tests work:
parquet-encryption-key-management-test
parquet-encryption-test
This removes a lot of confusion, as there are encryption_internal and internal_file_encryptor files. 
In the next PR I can make the intended change, which is to have the AesEncryptors inherit from the new EncryptorInterface.
=> Refactor aes encryptor

cpp/src/parquet/encryption/aes_encryption.cc, cpp/src/parquet/encryption/encryption.h, cpp/src/parquet/encryption/external_dbpa_encryption.cc, cpp/src/parquet/encryption/external_dbpa_encryption.h, cpp/src/parquet/encryption/external_dbpa_encryption_test.cc, cpp/src/parquet/encryption/internal_file_encryptor.cc, cpp/src/parquet/encryption/internal_file_encryptor.h, cpp/src/parquet/encryption/write_configurations_test.cc, python/pyarrow/tests/parquet/test_external_encryption.py, python/scripts/base_app.py
Change Arrow code so that it checks whether a column is encrypted with its own specific algorithm.
Create an instance of ExternalDBPAEncryptorAdapter (using a new factory) when that is the case.
The encryption flow now works, but the decryption flow still needs to be set up. 
Proper testing will be done in the next PR when the decryption flow is complete.
Disabled two Python tests that were testing roundtrip, since those are failing now.
=> Integrating the ExternalDBPAEncryptorAdapter into the Arrow InternalEncryptor

cpp/src/parquet/encryption/internal_file_encryptor.cc
@cristekdatum is reporting a local build error that also makes some actions fail with:
dev-phase2/cpp/src/parquet/encryption/internal_file_encryptor.cc:154:64: error: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'int32_t' (aka 'int') [-Werror,-Wshorten-64-to-32]
return aes_encryptor_factory_.GetDataAesEncryptor(algorithm, key_size);
My local build works, but adding an explicit cast to fix others.
=> Fixing compiler warning/error around int precision loss

cpp/src/parquet/encryption/properties_test.cc
Modifying how the `External*PropertiesBuilders` are used to prevent issues with eager de-allocation of the builder (due to it being considered a temporary object). This only affects the tests today.
Further explanation below (original code to help illustrate)
```
[443]  parquet::ExternalFileDecryptionProperties::Builder* builder =
[444]      parquet::ExternalFileDecryptionProperties::Builder()
[445]          .footer_key(kFooterEncryptionKey)
[446]          ->plaintext_files_allowed()
[447]          ->key_retriever(kr1);
[448]  std::shared_ptr<parquet::ExternalFileDecryptionProperties> props = builder->build_external();
```
The `builder` instance generated in line 443 is considered by the C++ compiler a "temporary object". There is no guarantee that temporary objects will survive the …
=> Modifying how the External*PropertiesBuilders in tests

cpp/src/parquet/encryption/external/dbpa_utils.cc, cpp/src/parquet/encryption/external/dbpa_utils.h
Adding `parquet/encryption/external/dbpa_utils.*` for translating enum values between the Arrow and DBPS namespaces
This code is to be used by the new implementation of `ExternalDBPAEncryptorAdapter` and `ExternalDBPADecryptorAdapter` to generate new DBPA instances.
Existing tests pass. Not sure that writing tests for the limited functionality of the new code makes sense (given that it's simple translation).
=> Adding external/dbpa_utils.* for translating enum values between the Arrow and DBPS namespaces

cpp/src/parquet/CMakeLists.txt, cpp/src/parquet/encryption/external/dbpa_utils.h, cpp/src/parquet/encryption/external_dbpa_encryption.cc, cpp/src/parquet/encryption/external_dbpa_encryption.h, cpp/src/parquet/encryption/external_dbpa_encryption_test.cc, cpp/src/parquet/encryption/read_configurations_test.cc, cpp/src/parquet/encryption/write_configurations_test.cc
Modifying ExternalDBPAEncryptor/DecryptorAdapter to obtain agent instance from shared lib (DLL)
This is the last piece which connects together the base work in Arrow (`dev_phase2`), and DLL-based agent loading. 
Both `ExternalDBPAEncryptorAdapter` and `ExternalDBPADecryptorAdapter` have been modified to abandon the simple, pass-through encryption/decryption, and to make use of the DLL-loaded agent (which must be specific in the `connection_config` object passed in. The modifications include (a) looking for the DLL-file name in the properties, (b) instantiating a new agent from the DLL, and (c) forwarding the encrypt/decrypt operations to the DLL-based agent.
**Testing**
- Tests inside `external_dbpa_encryption_tests.cc` had to be modified to account for the need of DLL. For these tests, …
=> Modifying ExternalDBPAEncryptor/DecryptorAdapter to obtain agent instance from shared lib (DLL)

cpp/src/parquet/CMakeLists.txt, cpp/src/parquet/encryption/CMakeLists.txt, cpp/src/parquet/encryption/external/dbpa_executor.cc, cpp/src/parquet/encryption/external/dbpa_executor.h, cpp/src/parquet/encryption/external/dbpa_executor_test.cc
Defining `DBPAExecutor`, a decorator which ensures that operations of DBPA instances complete in a deterministic amount of time. 
**Motivation**
- The behavior of internal encryptors (e.g. AES) is well understood and controlled heavily at compile time. External Encryptors do not offer the same guarantees around execution (e.g. some operations in external encryptors may take a long time to complete, or may never complete). We want to protect Arrow to ensure that operations in external encryptors complete within a known amount of time.
- Relevant Issue: https://github.com/protegrity/arrow/issues/146
**Useful Context**
- During the Write Column operation, if there are failures (i.e. exceptions thrown) while writing **any** Chunk/Page, Arrow will stop the Write Column operation, and will also …
=> Defining DBPAExecutor

cpp/src/parquet/encryption/external/dbpa_executor.cc, cpp/src/parquet/encryption/external/dbpa_executor.h, cpp/src/parquet/encryption/external/dbpa_executor_test.cc, cpp/src/parquet/encryption/external/dbpa_library_wrapper.h, cpp/src/parquet/encryption/external/dbpa_library_wrapper_test.cc, cpp/src/parquet/encryption/external/dbpa_test_agent.cc, cpp/src/parquet/encryption/external/dbpa_test_agent.h, cpp/src/parquet/encryption/external/third_party/dbpa_interface.h, cpp/src/parquet/encryption/external_dbpa_encryption.cc, cpp/src/parquet/encryption/external_dbpa_encryption.h, cpp/src/parquet/encryption/external_dbpa_encryption_test.cc
Importing the latest version of DBPAInterface.
**Changes**
- The signature for `init()`, `encrypt()` and `decrypt()` changed. `init()` added a new `datatype_length` parameter, and `decrypt()` and `encrypt()` added a `encoding attributes` parameter. Made the necessary adjustments in this PR.
- Wired in the `datatype_length` parameter all the way down to the encryptor/decryptor.
**Testing**
- Existing and modified tests pass (via `cmake -L parquet`)
- Additional tests which exercise the new params and datatypelength fields will be written in an upcoming PR.
=> Importing the latest DBPAInterface

cpp/src/parquet/encryption/encoding_properties.cc, cpp/src/parquet/encryption/encoding_properties.h
In encryption_encodings.cc - for enum types, adding the string representation to ToPropertiesMap()
**Testing**
- Existing tests pass (via `ctest -L parquet`)
- Manual testing using `base_app.py`
- More comprehensive tests for `encoding_properties.*` will be part of a future PR.
=> Adding the string representation to ToPropertiesMap()

cpp/src/parquet/CMakeLists.txt, cpp/src/parquet/column_writer.cc, cpp/src/parquet/column_writer_test.cc, cpp/src/parquet/encryption/aes_encryption.h, cpp/src/parquet/encryption/aes_encryption_test.cc, cpp/src/parquet/encryption/encryptor_interface.h, cpp/src/parquet/encryption/external_dbpa_encryption.cc, cpp/src/parquet/encryption/external_dbpa_encryption.h, cpp/src/parquet/encryption/external_dbpa_encryption_test.cc, cpp/src/parquet/encryption/internal_file_encryptor.cc, cpp/src/parquet/encryption/internal_file_encryptor.h, cpp/src/parquet/metadata.cc, cpp/src/parquet/thrift_internal.h
Updating encryptor interfaces and implementations so that we can signal whether an encryptor can calculate the ciphertext length before calling the actual encryption.
Added another method for when the encryptor cannot make this calculation, called EncryptWithManagedBuffer. This takes a ResizableBuffer that the encryptor is responsible for managing, resizing, and copying the results during the encryption call.
Encryptors can only implement one of the encrypt call (regular or with managed buffer). The other call should throw an exception.
Modified tests accordingly, testing round trip on the column_writer_test. The changes made in metadata and thrift_internal as tested as part of the round trip test.
See the [document](https://docs.google.com/document/d/1e5VwLyWmjuqPR6wi6UJm0JhLdU7VSn920HjaR …
=> Ciphertext length solution

cpp/src/parquet/encryption/CMakeLists.txt, cpp/src/parquet/encryption/external_dbpa_encryption_it.cc
Creating `external_dbpa_encryption_it.cc` as an integration test which exercises an instance of remote DBPS against several combinations of parameters (page type, encoding, compression, data type, etc)
**Testing**
- All combinations exercised by this new testing framework successfully "pass"
**Notes**
- See attached `dbps_server_output.txt` to see the output captured on a local DBPS instance when running the test
- See attached `test_summary.txt` to see the order and configuration of the different params.
**Attachments**
- [dbps_server_output.txt](https://github.com/user-attachments/files/22649910/dbps_server_output.txt)
- [test_summary.txt](https://github.com/user-attachments/files/22649911/test_summary.txt)
=> Creating external_dbpa_encryption_integ_test.cc for testing combination of encoding parameters.

cpp/src/parquet/encryption/read_configurations_test.cc
Adding keys to Decryption test # 6 in read_configuration_test.cc to avoid validation issues in FileDecryptionProperties() (encryption.cc)
Issues only arise when compiling with `-DCMAKE_BUILD_TYPE=Debug`
After this change, all tests in `ctest -L parquet` pass (after compiling with `-DCMAKE_BUILD_TYPE=Debug`)
=> Fixing issues in read_configuration_test

cpp/src/parquet/column_reader.cc, cpp/src/parquet/encryption/aes_encryption.h, cpp/src/parquet/encryption/aes_encryption_test.cc, cpp/src/parquet/encryption/decryptor_interface.h, cpp/src/parquet/encryption/external_dbpa_encryption.cc, cpp/src/parquet/encryption/external_dbpa_encryption.h, cpp/src/parquet/encryption/external_dbpa_encryption_test.cc, cpp/src/parquet/encryption/internal_file_decryptor.cc, cpp/src/parquet/encryption/internal_file_decryptor.h, cpp/src/parquet/file_deserialize_test.cc, cpp/src/parquet/thrift_internal.h
Updating decryptor interfaces and implementations so that we can signal whether a decryptor can calculate the plaintext length before calling the actual decryption.
Added another method for when the decryptor cannot make this calculation, called DecryptWithManagedBuffer. This takes a ResizableBuffer that the decryptor is responsible for managing, resizing, and copying the results during the decryption call.
Decryptors can only implement one of the decrypt call (regular or with managed buffer). The other call should throw an exception.
Modified tests accordingly, the round trip test for this has already been done in column_writer_test.
=> Adding plaintext solution to decrypt path

cpp/src/parquet/encryption/external_dbpa_encryption.cc, cpp/src/parquet/encryption/external_dbpa_encryption_test.cc, python/scripts/base_app.py, python/scripts/test_connection_config_file.json
Adding timeout values to the connection config under keys:
- init_timeout_ms
- encrypt_timeout_ms
- decrypt_timeout_ms
There are default values associated with them, but if the keys are present (they are optional), the values are overwritten.
=> Extracting timeout values from the connection config file
